### PR TITLE
Upgrade to rails 4.1.9

### PR DESCRIPTION
**Pull request by jvanbaarsen**
**What does this PR do?**
It upgrades GitLab CI to rails 4.1.9 (latest in the 4.1.x series).

I needed to fix some code since `Object.relation.count` does not work anymore, so I had to change it to `Object.relation.count(:all)`.

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
@dblessing Can you review?

**Comment by dosire** [comment]
Thanks for this upgrade @jvanbaarsen

**Comment by randx** [comment]
@jvanbaarsen thank you

**Comment by randx** [comment]
cc @vsizov

**Pull request merged**
