### PR TITLE
Removed deprecated API behaviour

### PR DESCRIPTION
**Pull request by jvanbaarsen**
**What does this PR do?**
It removes an API endpoint that was marked as deprecated.

**Points the reviewer needs to be extra careful about?**
Yeah, we should be 100% certain that this API is actually deprecated. @randx can you confirm?

### CODE REVIEW

**Comment by randx** [comment]
Yes  I can confirm. User should create build via commit endpoint now

**Comment by Razer6** [comment]
@jvanbaarsen Maybe you can add this also to he changelog

**Comment by jvanbaarsen** [comment]
@Razer6 Good point! Will do.

**Comment by randx** [comment]
cc @vsizov

**Comment by vsizov** [comment]
Thank you

**Pull request merged**
